name: Pre-Integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - "20"
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Tag
        id: gettag
        run: |
          sudo apt-get install jq
          echo ::set-output name=tag_val::v$(cat ./package.json | jq -r ".version")
      - name: Mock Publish
        run: |
          echo "Would now publish tag: ${{ steps.gettag.outputs.tag_val }}"
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Rebuild the webpack
        run: |
          npm install

      - name: zip
        run: |
          sudo apt install zip
          zip -r rwk.zip rwk


