name: Pre-Integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - "16"
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install --ignore-scripts
      - run: npm run pack
      - run: npm run build
      - run: npm run setup yes
