name: Release

on:
 workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - "20"
    steps:
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - uses: actions/checkout@v2

      - name: Rebuild the webpack
        run: |
          npm install
      - name: zip
        run: |
          sudo apt install zip
          zip -r rwk.zip rwk
      - name: Prepare Tag
        id: gettag
        run: |
          sudo apt-get install jq
          echo ::set-output name=tag_val::v$(cat ./package.json | jq -r ".version")
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: rwk.zip
          name: RWK Tiled Plugin
          tag_name: ${{ steps.gettag.outputs.tag_val }}
          body_path: docs/INSTALLATION.md
          draft: false
          
